# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/panpan/github/archpm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/panpan/github/archpm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panpan/github/archpm/CMakeFiles /home/panpan/github/archpm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panpan/github/archpm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named archpm

# Build rule for target.
archpm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archpm
.PHONY : archpm

# fast build rule for target.
archpm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/build
.PHONY : archpm/fast

#=============================================================================
# Target rules for targets named archpm_autogen

# Build rule for target.
archpm_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archpm_autogen
.PHONY : archpm_autogen

# fast build rule for target.
archpm_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm_autogen.dir/build.make CMakeFiles/archpm_autogen.dir/build
.PHONY : archpm_autogen/fast

archpm_autogen/mocs_compilation.o: archpm_autogen/mocs_compilation.cpp.o
.PHONY : archpm_autogen/mocs_compilation.o

# target to build an object file
archpm_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/archpm_autogen/mocs_compilation.cpp.o
.PHONY : archpm_autogen/mocs_compilation.cpp.o

archpm_autogen/mocs_compilation.i: archpm_autogen/mocs_compilation.cpp.i
.PHONY : archpm_autogen/mocs_compilation.i

# target to preprocess a source file
archpm_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/archpm_autogen/mocs_compilation.cpp.i
.PHONY : archpm_autogen/mocs_compilation.cpp.i

archpm_autogen/mocs_compilation.s: archpm_autogen/mocs_compilation.cpp.s
.PHONY : archpm_autogen/mocs_compilation.s

# target to generate assembly for a file
archpm_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/archpm_autogen/mocs_compilation.cpp.s
.PHONY : archpm_autogen/mocs_compilation.cpp.s

src/config.o: src/config.cc.o
.PHONY : src/config.o

# target to build an object file
src/config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/config.cc.o
.PHONY : src/config.cc.o

src/config.i: src/config.cc.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/config.cc.i
.PHONY : src/config.cc.i

src/config.s: src/config.cc.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/config.cc.s
.PHONY : src/config.cc.s

src/dialog.o: src/dialog.cc.o
.PHONY : src/dialog.o

# target to build an object file
src/dialog.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/dialog.cc.o
.PHONY : src/dialog.cc.o

src/dialog.i: src/dialog.cc.i
.PHONY : src/dialog.i

# target to preprocess a source file
src/dialog.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/dialog.cc.i
.PHONY : src/dialog.cc.i

src/dialog.s: src/dialog.cc.s
.PHONY : src/dialog.s

# target to generate assembly for a file
src/dialog.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/dialog.cc.s
.PHONY : src/dialog.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/mainwindow.o: src/mainwindow.cc.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/mainwindow.cc.o
.PHONY : src/mainwindow.cc.o

src/mainwindow.i: src/mainwindow.cc.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/mainwindow.cc.i
.PHONY : src/mainwindow.cc.i

src/mainwindow.s: src/mainwindow.cc.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/mainwindow.cc.s
.PHONY : src/mainwindow.cc.s

src/monitor.o: src/monitor.cc.o
.PHONY : src/monitor.o

# target to build an object file
src/monitor.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/monitor.cc.o
.PHONY : src/monitor.cc.o

src/monitor.i: src/monitor.cc.i
.PHONY : src/monitor.i

# target to preprocess a source file
src/monitor.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/monitor.cc.i
.PHONY : src/monitor.cc.i

src/monitor.s: src/monitor.cc.s
.PHONY : src/monitor.s

# target to generate assembly for a file
src/monitor.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/monitor.cc.s
.PHONY : src/monitor.cc.s

src/pkg_entry.o: src/pkg_entry.cc.o
.PHONY : src/pkg_entry.o

# target to build an object file
src/pkg_entry.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_entry.cc.o
.PHONY : src/pkg_entry.cc.o

src/pkg_entry.i: src/pkg_entry.cc.i
.PHONY : src/pkg_entry.i

# target to preprocess a source file
src/pkg_entry.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_entry.cc.i
.PHONY : src/pkg_entry.cc.i

src/pkg_entry.s: src/pkg_entry.cc.s
.PHONY : src/pkg_entry.s

# target to generate assembly for a file
src/pkg_entry.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_entry.cc.s
.PHONY : src/pkg_entry.cc.s

src/pkg_info.o: src/pkg_info.cc.o
.PHONY : src/pkg_info.o

# target to build an object file
src/pkg_info.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_info.cc.o
.PHONY : src/pkg_info.cc.o

src/pkg_info.i: src/pkg_info.cc.i
.PHONY : src/pkg_info.i

# target to preprocess a source file
src/pkg_info.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_info.cc.i
.PHONY : src/pkg_info.cc.i

src/pkg_info.s: src/pkg_info.cc.s
.PHONY : src/pkg_info.s

# target to generate assembly for a file
src/pkg_info.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_info.cc.s
.PHONY : src/pkg_info.cc.s

src/pkg_note.o: src/pkg_note.cc.o
.PHONY : src/pkg_note.o

# target to build an object file
src/pkg_note.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_note.cc.o
.PHONY : src/pkg_note.cc.o

src/pkg_note.i: src/pkg_note.cc.i
.PHONY : src/pkg_note.i

# target to preprocess a source file
src/pkg_note.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_note.cc.i
.PHONY : src/pkg_note.cc.i

src/pkg_note.s: src/pkg_note.cc.s
.PHONY : src/pkg_note.s

# target to generate assembly for a file
src/pkg_note.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pkg_note.cc.s
.PHONY : src/pkg_note.cc.s

src/pm/cb.o: src/pm/cb.cpp.o
.PHONY : src/pm/cb.o

# target to build an object file
src/pm/cb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/cb.cpp.o
.PHONY : src/pm/cb.cpp.o

src/pm/cb.i: src/pm/cb.cpp.i
.PHONY : src/pm/cb.i

# target to preprocess a source file
src/pm/cb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/cb.cpp.i
.PHONY : src/pm/cb.cpp.i

src/pm/cb.s: src/pm/cb.cpp.s
.PHONY : src/pm/cb.s

# target to generate assembly for a file
src/pm/cb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/cb.cpp.s
.PHONY : src/pm/cb.cpp.s

src/pm/conf.o: src/pm/conf.cpp.o
.PHONY : src/pm/conf.o

# target to build an object file
src/pm/conf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/conf.cpp.o
.PHONY : src/pm/conf.cpp.o

src/pm/conf.i: src/pm/conf.cpp.i
.PHONY : src/pm/conf.i

# target to preprocess a source file
src/pm/conf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/conf.cpp.i
.PHONY : src/pm/conf.cpp.i

src/pm/conf.s: src/pm/conf.cpp.s
.PHONY : src/pm/conf.s

# target to generate assembly for a file
src/pm/conf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/conf.cpp.s
.PHONY : src/pm/conf.cpp.s

src/pm/debug.o: src/pm/debug.cpp.o
.PHONY : src/pm/debug.o

# target to build an object file
src/pm/debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/debug.cpp.o
.PHONY : src/pm/debug.cpp.o

src/pm/debug.i: src/pm/debug.cpp.i
.PHONY : src/pm/debug.i

# target to preprocess a source file
src/pm/debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/debug.cpp.i
.PHONY : src/pm/debug.cpp.i

src/pm/debug.s: src/pm/debug.cpp.s
.PHONY : src/pm/debug.s

# target to generate assembly for a file
src/pm/debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/debug.cpp.s
.PHONY : src/pm/debug.cpp.s

src/pm/interface.o: src/pm/interface.cpp.o
.PHONY : src/pm/interface.o

# target to build an object file
src/pm/interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/interface.cpp.o
.PHONY : src/pm/interface.cpp.o

src/pm/interface.i: src/pm/interface.cpp.i
.PHONY : src/pm/interface.i

# target to preprocess a source file
src/pm/interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/interface.cpp.i
.PHONY : src/pm/interface.cpp.i

src/pm/interface.s: src/pm/interface.cpp.s
.PHONY : src/pm/interface.s

# target to generate assembly for a file
src/pm/interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/interface.cpp.s
.PHONY : src/pm/interface.cpp.s

src/pm/parse.o: src/pm/parse.cpp.o
.PHONY : src/pm/parse.o

# target to build an object file
src/pm/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/parse.cpp.o
.PHONY : src/pm/parse.cpp.o

src/pm/parse.i: src/pm/parse.cpp.i
.PHONY : src/pm/parse.i

# target to preprocess a source file
src/pm/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/parse.cpp.i
.PHONY : src/pm/parse.cpp.i

src/pm/parse.s: src/pm/parse.cpp.s
.PHONY : src/pm/parse.s

# target to generate assembly for a file
src/pm/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/parse.cpp.s
.PHONY : src/pm/parse.cpp.s

src/pm/util.o: src/pm/util.cpp.o
.PHONY : src/pm/util.o

# target to build an object file
src/pm/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/util.cpp.o
.PHONY : src/pm/util.cpp.o

src/pm/util.i: src/pm/util.cpp.i
.PHONY : src/pm/util.i

# target to preprocess a source file
src/pm/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/util.cpp.i
.PHONY : src/pm/util.cpp.i

src/pm/util.s: src/pm/util.cpp.s
.PHONY : src/pm/util.s

# target to generate assembly for a file
src/pm/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/archpm.dir/build.make CMakeFiles/archpm.dir/src/pm/util.cpp.s
.PHONY : src/pm/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... archpm_autogen"
	@echo "... archpm"
	@echo "... archpm_autogen/mocs_compilation.o"
	@echo "... archpm_autogen/mocs_compilation.i"
	@echo "... archpm_autogen/mocs_compilation.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/dialog.o"
	@echo "... src/dialog.i"
	@echo "... src/dialog.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/monitor.o"
	@echo "... src/monitor.i"
	@echo "... src/monitor.s"
	@echo "... src/pkg_entry.o"
	@echo "... src/pkg_entry.i"
	@echo "... src/pkg_entry.s"
	@echo "... src/pkg_info.o"
	@echo "... src/pkg_info.i"
	@echo "... src/pkg_info.s"
	@echo "... src/pkg_note.o"
	@echo "... src/pkg_note.i"
	@echo "... src/pkg_note.s"
	@echo "... src/pm/cb.o"
	@echo "... src/pm/cb.i"
	@echo "... src/pm/cb.s"
	@echo "... src/pm/conf.o"
	@echo "... src/pm/conf.i"
	@echo "... src/pm/conf.s"
	@echo "... src/pm/debug.o"
	@echo "... src/pm/debug.i"
	@echo "... src/pm/debug.s"
	@echo "... src/pm/interface.o"
	@echo "... src/pm/interface.i"
	@echo "... src/pm/interface.s"
	@echo "... src/pm/parse.o"
	@echo "... src/pm/parse.i"
	@echo "... src/pm/parse.s"
	@echo "... src/pm/util.o"
	@echo "... src/pm/util.i"
	@echo "... src/pm/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

